# Generated by Django 4.2.5 on 2024-01-18 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='password',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='schoolname',
        ),
    ]
