# Generated by Django 4.2.5 on 2024-01-18 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_password_userprofile_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='students',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='number',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='schoolname',
            new_name='school',
        ),
    ]
