# Generated by Django 4.2.5 on 2024-01-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_userprofile_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='class_num',
            field=models.CharField(default=int, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='grade',
            field=models.CharField(default=int, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='number',
            field=models.CharField(default=int, max_length=255),
            preserve_default=False,
        ),
    ]
