# Generated by Django 4.2.5 on 2024-01-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_students_class_num_students_grade_students_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255)),
                ('grade', models.IntegerField()),
                ('class_num', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='students',
        ),
    ]
