# Generated by Django 4.2.5 on 2024-01-22 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_student_delete_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False},
        ),
    ]
