# Generated by Django 4.2.5 on 2024-01-22 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
