# Generated by Django 4.2.5 on 2024-01-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('uid', models.CharField(db_column='uid', max_length=255, primary_key=True, serialize=False)),
                ('name', models.IntegerField(db_column='name')),
                ('school', models.CharField(db_column='school', max_length=255)),
                ('grade', models.IntegerField(db_column='grade')),
                ('class_num', models.IntegerField(db_column='class_num')),
                ('number', models.IntegerField(db_column='number')),
                ('gender', models.BooleanField(db_column='gender')),
            ],
        ),
    ]
