# Generated by Django 4.2.5 on 2024-01-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_student_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=255)),
                ('game_type', models.CharField(max_length=255)),
                ('start_ts', models.DateTimeField()),
                ('finish_ts', models.DateTimeField()),
            ],
            options={
                'db_table': 'game_records',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
