# Generated by Django 4.2.5 on 2024-03-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_gamerecord_alter_student_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='InBodyRecord',
            fields=[
                ('record_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=30)),
                ('timestamp', models.BigIntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('fat', models.FloatField()),
                ('fat_ratio', models.FloatField()),
                ('muscle', models.FloatField()),
                ('skeletal_muscle', models.FloatField()),
                ('water_content', models.FloatField()),
                ('bmi', models.FloatField()),
            ],
            options={
                'db_table': 'inbody_records',
                'managed': False,
            },
        ),
    ]
