# Generated by Django 4.2.5 on 2024-01-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=255)),
                ('game_type', models.CharField(max_length=255)),
                ('start_ts', models.IntegerField()),
                ('finish_ts', models.IntegerField()),
            ],
            options={
                'db_table': 'game_records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('uid', models.CharField(db_column='uid', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name')),
                ('school', models.CharField(db_column='school', max_length=255)),
                ('grade', models.IntegerField(db_column='grade')),
                ('class_num', models.IntegerField(db_column='class_num')),
                ('number', models.IntegerField(db_column='number')),
                ('gender', models.BooleanField(db_column='gender')),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
    ]
