# Generated by Django 5.0.6 on 2024-07-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartmirror', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='game_table',
            fields=[
                ('record_id', models.AutoField(db_column='record_id', primary_key=True, serialize=False)),
                ('uid', models.CharField(db_column='uid', max_length=255)),
                ('game_name', models.CharField(db_column='game_name', max_length=255)),
                ('game_type', models.CharField(db_column='game_type', max_length=255)),
                ('play_time', models.IntegerField(db_column='play_time')),
                ('correct_score', models.IntegerField(db_column='correct_score')),
                ('fail_score', models.IntegerField(db_column='fail_score')),
                ('start_ts', models.IntegerField(db_column='start_ts')),
                ('finish_ts', models.IntegerField(db_column='finish_ts')),
            ],
            options={
                'db_table': 'game_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='stretch_table',
            fields=[
                ('record_id', models.AutoField(db_column='record_id', primary_key=True, serialize=False)),
                ('uid', models.CharField(db_column='uid', max_length=255)),
                ('stretch_name', models.CharField(db_column='stretch_name', max_length=255)),
                ('stretch_type', models.CharField(db_column='stretch_type', max_length=255)),
                ('stretch_time', models.IntegerField(db_column='stretch_time')),
                ('acc_average', models.IntegerField(db_column='acc_average')),
                ('start_ts', models.IntegerField(db_column='start_ts')),
                ('finish_ts', models.IntegerField(db_column='finish_ts')),
            ],
            options={
                'db_table': 'stretch_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('uid', models.CharField(db_column='uid', max_length=255, primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_column='user_name', max_length=255)),
                ('center_name', models.CharField(db_column='center_name', max_length=255)),
                ('birth', models.IntegerField(db_column='birth')),
                ('gender', models.BooleanField(db_column='gender')),
            ],
            options={
                'db_table': 'user_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='walk_table',
            fields=[
                ('record_id', models.AutoField(db_column='record_id', primary_key=True, serialize=False)),
                ('uid', models.CharField(db_column='uid', max_length=255)),
                ('walk_name', models.CharField(db_column='walk_name', max_length=255)),
                ('walk_time', models.IntegerField(db_column='walk_time')),
                ('walk_count', models.IntegerField(db_column='walk_count')),
                ('velocity', models.IntegerField(db_column='velocity')),
                ('start_ts', models.IntegerField(db_column='start_ts')),
                ('finish_ts', models.IntegerField(db_column='finish_ts')),
            ],
            options={
                'db_table': 'walk_table',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='GameRecord',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
