# Generated by Django 5.1.6 on 2025-03-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartmirror', '0002_game_table_stretch_table_user_table_walk_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='center_table',
            fields=[
                ('center_id', models.AutoField(db_column='center_id', primary_key=True, serialize=False)),
                ('center_name', models.CharField(db_column='center_name', max_length=255)),
                ('center_password', models.CharField(db_column='center_password', max_length=255)),
            ],
            options={
                'db_table': 'center_table',
                'managed': False,
            },
        ),
    ]
